spring:
  application:
    name: event-notification-service
  mongodb:
    database: events_db
    uri: mongodb+srv://notzaidcodes_db_user:qTNShA86njR70Vjv@cluster0.sqw8zsg.mongodb.net/?appName=Cluster0

server:
  port: 9090